services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - my-network

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
