services:
  my-postgres:
    image: postgres:latest
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the script here
    ports:
      - "5432:5432"

volumes:
  postgres_data:
